### PR TITLE
25 remove classes

### LINKED ISSUE #25: Remove classes and just use objects/factory functions

### PR DESCRIPTION
**Pull request by alitnk**
Closes #25 

There are a lot of changes but I think the only ones that affect the users of the package are:
- There's no second arg on `getPaymentDriver` - It returns a new function now. here's an example:
  - old: `getPaymentDriver('zibal', { configItem: '123' })`
  - new: `getPaymentDriver('zibal')({ configItem: '123' })`
- Receipt's `raw` property is no longer type-safe - it's just `any` now
- `driver.requestPayment()` => `driver.request()`
- `driver.verifyPayment()` => `driver.verify()`

The features added:
- The users now can override "links" when configuring the driver. This way they can use their custom gateway link (e.g. from https://banktest.ir/)
  - `getPaymentDriver('zibal')({ links: { request: "https://my.link/request", verify: ..., payment: ... } })`
  

Let me know if you have any ideas/concerns on the changes

### CODE REVIEW

**Comment by alitnk** [comment]
I think we could still keep `requestPayment` and `verifyPayment`, call the new `request` and `verify` functions under the hood and just mark them as deprecated.

**Comment by Keivan-sf** [comment]
Code is much readable now, nice job

I agree with keeping `requestPayment` and `verifyPayment`. A major change must be made softly for the users. We can delete them in the following updates later.

However [driver.ts](https://github.com/alitnk/monopay/pull/33/files#diff-bda213326e78e9028995e292a6a51a3fa201bce4a8dd750adad751ee572e4924) is a little complicated to read at first. I'm assuming we can have a script builder function in the `utils` since you've created it now to simplify the `getScript` a little. Also the `defineDriver` parameter can have a predefined type to decrease nesting a little bit.

That's it. I think clearing [driver.ts](https://github.com/alitnk/monopay/pull/33/files#diff-bda213326e78e9028995e292a6a51a3fa201bce4a8dd750adad751ee572e4924) clutter should do the job for us

**Comment by Keivan-sf** [comment]
If you're having the same thoughts I'll get on it

**Comment by alitnk** [comment]
Great call! Yeah you can do it if you want to.

**Comment by Keivan-sf** [comment]
I've tried to define types for the function parameters but since they're dependent to function generic types itself, they have to be defined with it like this : 
```ts
type DefineDriver = <
  DriverConfigSchema extends ZodSchema,
  DriverRequestSchema extends ZodSchema,
  DriverVerifySchema extends ZodSchema,
  IConfig extends z.infer<DriverConfigSchema> & BaseConfigOptions,
  IRequest extends z.infer<DriverRequestSchema> & BaseRequestOptions,
  IVerify extends z.infer<DriverVerifySchema> & BaseVerifyOptions,
  DefaultConfig extends Partial<IConfig>,
>(param: {
  schema: { config: DriverConfigSchema; request: DriverRequestSchema; verify: DriverVerifySchema };
  defaultConfig: DefaultConfig;
  request: (arg: { ctx: IConfig; options: IRequest }) => Promise<IPaymentInfo>;
  verify: (arg: { ctx: IConfig; options: IVerify; params: Record<string, any> }) => Promise<BaseReceipt>;
}) => (config: Omit<IConfig, keyof DefaultConfig> & Partial<DefaultConfig>) => {
  request: (options: IRequest) => Promise<{
    getScript: () => string;
    referenceId: string | number;
    method: 'GET' | 'POST';
    url: string;
    params?: Record<string, any> | undefined;
  }>;
  verify: (options: IVerify, params: Record<string, any>) => Promise<BaseReceipt<any>>;
  verifyPayment: (options: IVerify, params: Record<string, any>) => Promise<BaseReceipt<any>>;
  requestPayment: (options: IRequest) => Promise<{
    getScript: () => string;
    referenceId: string | number;
    method: 'GET' | 'POST';
    url: string;
    params?: Record<string, any> | undefined;
  }>;
};
```
Which obviously does not make any difference in terms of nesting.
I think we should leave it be

**Comment by alitnk** [comment]
Yeah just let TS inference do its thing - We don't really have any reason to define types for it.

**Review by Keivan-sf — APPROVED** [review]
Everything seems good

**Pull request merged**
